/**
 * Decision Constellation — filtering and derivation.
 *
 * Pure functions, no DOM and no d3. Everything the map shows is decided
 * here; the canvas component only draws it. That split is what makes the
 * prototype's behaviour testable — `__fixtures__/reference.json` was
 * generated by running the original HTML's own filtering logic in Node, and
 * the tests assert this module reproduces it exactly.
 *
 * Two behaviours look like bugs and are the prototype's, kept deliberately:
 *
 *  - **Deselecting every system shows nothing, but the sheet label still
 *    reads "· 0 systems"** rather than a "no system selected" message, unlike
 *    the department and spine cases. Pinned by the `noSystems` scenario.
 *  - **A decision survives the system filter if *any* of its systems is
 *    selected**, not all of them — so unticking ERP does not remove every
 *    ERP-touching decision, only those that draw on nothing else. That is
 *    what makes the "untick ERP and see what is left" move work.
 */

import {
  isDecision,
  type Band,
  type ConstellationDataset,
  type ConstellationLink,
  type ConstellationNode,
  type DecisionNode,
  type HubNode,
  type LinkKind
} from './types';

export interface FilterState {
  bands: ReadonlySet<Band>;
  departments: ReadonlySet<string>;
  spines: ReadonlySet<string>;
  systems: ReadonlySet<string>;
  kinds: ReadonlySet<LinkKind>;
  minPriority: number;
  query: string;
}

export interface SystemGroup {
  name: string;
  systems: HubNode[];
}

/**
 * Everything derivable from the dataset once, so filtering does not walk
 * 863 links on every keystroke.
 */
export interface ConstellationIndex {
  decisions: DecisionNode[];
  /** In dataset order — the order the business reads in, not alphabetical. */
  departments: string[];
  departmentCounts: Record<string, number>;
  /** Busiest spine first. */
  spines: string[];
  spineCounts: Record<string, number>;
  systems: HubNode[];
  /** Tiers, most-attached first, each sorted by degree. */
  systemGroups: SystemGroup[];
  systemGroupOf: Record<string, string>;
  /** decision id → the system node ids it draws on. */
  decisionSystems: Record<string, string[]>;
  bandCounts: Record<Band, number>;
  nodeById: Record<string, ConstellationNode>;
}

export interface ConstellationGraph {
  nodes: ConstellationNode[];
  links: ConstellationLink[];
  /** Hub id → links reaching it in this view. Drives hub node size. */
  shown: Record<string, number>;
}

export interface GraphSummary {
  sheet: string;
  decisions: number;
  systems: number;
  links: number;
  /** One decimal, or an em dash when nothing is showing. */
  avgPriority: string;
}

const BAND_ORDER: readonly Band[] = ['Now', 'Next', 'Later', 'Watch'];

export function buildIndex(dataset: ConstellationDataset): ConstellationIndex {
  const decisions = dataset.nodes.filter(isDecision);

  const departments: string[] = [];
  const departmentCounts: Record<string, number> = {};
  const spineCounts: Record<string, number> = {};
  for (const d of decisions) {
    if (!(d.dept in departmentCounts)) departments.push(d.dept);
    departmentCounts[d.dept] = (departmentCounts[d.dept] ?? 0) + 1;
    spineCounts[d.spine] = (spineCounts[d.spine] ?? 0) + 1;
  }
  const spines = Object.keys(spineCounts).sort((a, b) => spineCounts[b] - spineCounts[a]);

  const systems = dataset.nodes.filter(
    (n): n is HubNode => n.type === 'system'
  );
  const systemGroupOf: Record<string, string> = {};
  const grouped = new Map<string, HubNode[]>();
  for (const s of systems) {
    const group = s.category || 'Other';
    systemGroupOf[s.id] = group;
    const bucket = grouped.get(group);
    if (bucket) bucket.push(s);
    else grouped.set(group, [s]);
  }
  const totalDegree = (list: HubNode[]) => list.reduce((t, s) => t + (s.degree || 0), 0);
  const systemGroups: SystemGroup[] = [...grouped.entries()]
    .sort((a, b) => totalDegree(b[1]) - totalDegree(a[1]))
    .map(([name, list]) => ({
      name,
      systems: list.slice().sort((a, b) => (b.degree || 0) - (a.degree || 0))
    }));

  const decisionSystems: Record<string, string[]> = {};
  for (const link of dataset.links) {
    if (link.kind !== 'system') continue;
    (decisionSystems[link.source] ??= []).push(link.target);
  }

  const bandCounts = Object.fromEntries(
    BAND_ORDER.map((band) => [band, decisions.filter((d) => d.band === band).length])
  ) as Record<Band, number>;

  const nodeById: Record<string, ConstellationNode> = {};
  for (const node of dataset.nodes) nodeById[node.id] = node;

  return {
    decisions,
    departments,
    departmentCounts,
    spines,
    spineCounts,
    systems,
    systemGroups,
    systemGroupOf,
    decisionSystems,
    bandCounts,
    nodeById
  };
}

/** Top two bands, everything else wide open — the prototype's opening view. */
export function defaultFilterState(
  index: ConstellationIndex,
  bands: readonly Band[] = ['Now', 'Next']
): FilterState {
  return {
    bands: new Set(bands),
    departments: new Set(index.departments),
    spines: new Set(index.spines),
    systems: new Set(index.systems.map((s) => s.id)),
    kinds: new Set<LinkKind>(['system', 'department', 'process']),
    minPriority: 0,
    query: ''
  };
}

export function visibleDecisions(
  index: ConstellationIndex,
  state: FilterState
): DecisionNode[] {
  const query = state.query.trim().toLowerCase();
  // With every system selected the system filter is a no-op, and skipping it
  // avoids a lookup per decision on the default view.
  const allSystems = state.systems.size === index.systems.length;

  return index.decisions.filter((d) => {
    if (!state.bands.has(d.band)) return false;
    if (!state.departments.has(d.dept)) return false;
    if (!state.spines.has(d.spine)) return false;
    if (d.priority < state.minPriority) return false;
    if (!allSystems && !(index.decisionSystems[d.id] ?? []).some((t) => state.systems.has(t))) {
      return false;
    }
    if (!query) return true;
    return (
      d.label.toLowerCase().includes(query) ||
      d.dept.toLowerCase().includes(query) ||
      d.metrics.toLowerCase().includes(query) ||
      d.primary.toLowerCase().includes(query) ||
      d.spine.toLowerCase().includes(query)
    );
  });
}

export function buildGraph(
  dataset: ConstellationDataset,
  index: ConstellationIndex,
  state: FilterState
): ConstellationGraph {
  const decisionIds = new Set(visibleDecisions(index, state).map((d) => d.id));

  const links = dataset.links.filter((l) => {
    if (!decisionIds.has(l.source)) return false;
    if (!state.kinds.has(l.kind)) return false;
    if (l.kind === 'system') return state.systems.has(l.target);
    return true;
  });

  const keep = new Set(decisionIds);
  const shown: Record<string, number> = {};
  for (const l of links) {
    keep.add(l.target);
    shown[l.target] = (shown[l.target] ?? 0) + 1;
  }

  // Dataset order, so the simulation seeds the same way every time.
  const nodes = dataset.nodes.filter((n) => keep.has(n.id));
  for (const n of nodes) shown[n.id] ??= 0;

  return { nodes, links, shown };
}

/**
 * The line in the title block. Reads as a drawing sheet name — what this
 * particular view of the map is.
 */
export function sheetLabel(
  index: ConstellationIndex,
  state: FilterState,
  focusId?: string | null
): string {
  if (focusId) return `Focus — ${focusId}`;

  const deptCount = state.departments.size;
  const departmentLabel =
    deptCount === index.departments.length
      ? 'Full map — all departments'
      : deptCount === 0
        ? 'No department selected'
        : deptCount === 1
          ? [...state.departments][0]
          : `${deptCount} departments`;

  const systemCount = state.systems.size;
  const systemSuffix =
    systemCount === index.systems.length
      ? ''
      : systemCount === 1
        ? ` · ${index.systems.find((s) => state.systems.has(s.id))?.label ?? ''} only`
        : ` · ${systemCount} systems`;

  const spineCount = state.spines.size;
  const head =
    spineCount === 0
      ? 'No process spine selected'
      : spineCount === 1
        ? [...state.spines][0] +
          (deptCount === index.departments.length ? '' : ` — ${departmentLabel}`)
        : departmentLabel;

  return head + systemSuffix;
}

export function summarise(
  index: ConstellationIndex,
  state: FilterState,
  graph: ConstellationGraph,
  focusId?: string | null
): GraphSummary {
  const decisions = graph.nodes.filter(isDecision);
  const systems = graph.nodes.filter((n) => n.type === 'system');
  return {
    sheet: sheetLabel(index, state, focusId),
    decisions: decisions.length,
    systems: systems.length,
    links: graph.links.length,
    avgPriority: decisions.length
      ? (decisions.reduce((a, b) => a + b.priority, 0) / decisions.length).toFixed(1)
      : '—'
  };
}

/**
 * The ego view: one decision, the department that owns it, the systems it
 * draws on and the process it sits in. Systems are laid out on the left and
 * the process on the right, which is the reading the focus bar promises.
 */
export function egoGraph(
  dataset: ConstellationDataset,
  decisionId: string
): ConstellationGraph {
  const links = dataset.links.filter((l) => l.source === decisionId);
  const ids = new Set([decisionId, ...links.map((l) => l.target)]);
  const nodes = dataset.nodes.filter((n) => ids.has(n.id));
  // Hubs in the ego view are all drawn the same size — the sizing that means
  // something on the full map is noise when there is only one decision.
  const shown: Record<string, number> = {};
  for (const n of nodes) shown[n.id] = 3;
  return { nodes, links, shown };
}

/** Decisions attached to a hub, highest priority first. */
export function decisionsForHub(
  dataset: ConstellationDataset,
  index: ConstellationIndex,
  hubId: string
): DecisionNode[] {
  const touching = new Set(
    dataset.links.filter((l) => l.target === hubId).map((l) => l.source)
  );
  return index.decisions
    .filter((d) => touching.has(d.id))
    .sort((a, b) => b.priority - a.priority);
}

/** Departments touching a hub, busiest first. */
export function departmentSpreadForHub(decisions: DecisionNode[]): [string, number][] {
  const counts: Record<string, number> = {};
  for (const d of decisions) counts[d.dept] = (counts[d.dept] ?? 0) + 1;
  return Object.entries(counts).sort((a, b) => b[1] - a[1]);
}

// ─── Process view ────────────────────────────────────────────────────────
//
// Isolating a single spine switches the map out of the force layout and into
// staged swimlanes: stage columns left to right in flow order, departments as
// lanes down the side. The point is that handoffs become visible — you can
// walk one spine stage by stage, which is the order the business actually
// makes its decisions in, and see where each one crosses a department.
//
// The geometry is computed here rather than in the canvas so it can be pinned
// against the prototype's own output, the same way the filtering is.

/**
 * The spine the process view applies to, or `null` for the constellation.
 *
 * Exactly one selected spine is the trigger — there is no separate toggle,
 * because the useful gesture in front of a client is "show me just
 * quote-to-cash", not "switch view mode". Two spines have no shared flow
 * order to lay out, so the constellation comes back on its own.
 */
export function activeProcessSpine(state: FilterState): string | null {
  return state.spines.size === 1 ? [...state.spines][0] : null;
}

export interface ProcessLane {
  dept: string;
  /** Decisions this department owns in this spine, across all stages. */
  count: number;
  y: number;
  height: number;
}

export interface PlacedDecision {
  decision: DecisionNode;
  x: number;
  y: number;
}

export interface ProcessLayout {
  spine: string;
  /** In flow order. Column i is `stages[i]`. */
  stages: string[];
  lanes: ProcessLane[];
  placed: PlacedDecision[];
  /** Stages with nothing in them under the current filters. */
  emptyStages: string[];
  decisions: number;
  avgPriority: string;
  totalWidth: number;
  totalHeight: number;
  columnX: (index: number) => number;
}

export function buildProcessLayout(
  dataset: ConstellationDataset,
  index: ConstellationIndex,
  state: FilterState,
  geometry: {
    columnWidth: number;
    rowStep: number;
    lanePadding: number;
    headerHeight: number;
    laneLabelWidth: number;
    nodeInset: number;
  }
): ProcessLayout | null {
  const spine = activeProcessSpine(state);
  if (!spine) return null;

  const stages = dataset.spineStages[spine] ?? [];
  const decisions = visibleDecisions(index, state).filter((d) => d.spine === spine);

  // Lanes are the departments present, busiest first. Insertion order breaks
  // ties, which keeps a lane from jumping when a filter changes.
  const byDept = new Map<string, DecisionNode[]>();
  for (const d of decisions) {
    const bucket = byDept.get(d.dept);
    if (bucket) bucket.push(d);
    else byDept.set(d.dept, [d]);
  }
  const laneOrder = [...byDept.keys()].sort(
    (a, b) => byDept.get(b)!.length - byDept.get(a)!.length
  );

  // One cell per department × stage, highest priority at the top of the cell.
  const cells = new Map<string, DecisionNode[]>();
  for (const d of decisions) {
    const key = `${d.dept}|${d.stage}`;
    const bucket = cells.get(key);
    if (bucket) bucket.push(d);
    else cells.set(key, [d]);
  }
  for (const bucket of cells.values()) bucket.sort((a, b) => b.priority - a.priority);

  // A lane is as tall as its busiest cell, so nothing overlaps and the lane
  // heights themselves show where the work piles up.
  const lanes: ProcessLane[] = [];
  let y = geometry.headerHeight;
  for (const dept of laneOrder) {
    const busiest = Math.max(
      1,
      ...stages.map((s) => cells.get(`${dept}|${s}`)?.length ?? 0)
    );
    const height = busiest * geometry.rowStep + geometry.lanePadding * 2;
    lanes.push({ dept, count: byDept.get(dept)!.length, y, height });
    y += height;
  }

  const columnX = (i: number) => geometry.laneLabelWidth + i * geometry.columnWidth;

  const placed: PlacedDecision[] = [];
  for (const lane of lanes) {
    stages.forEach((stage, column) => {
      const bucket = cells.get(`${lane.dept}|${stage}`) ?? [];
      bucket.forEach((decision, row) => {
        placed.push({
          decision,
          x: columnX(column) + geometry.nodeInset,
          y: lane.y + geometry.lanePadding + 12 + row * geometry.rowStep
        });
      });
    });
  }

  return {
    spine,
    stages,
    lanes,
    placed,
    emptyStages: stages.filter((s) => !decisions.some((d) => d.stage === s)),
    decisions: decisions.length,
    avgPriority: decisions.length
      ? (decisions.reduce((a, b) => a + b.priority, 0) / decisions.length).toFixed(1)
      : '—',
    totalWidth: geometry.laneLabelWidth + stages.length * geometry.columnWidth,
    totalHeight: y,
    columnX
  };
}

/**
 * A decision's label as it appears beside its node in the process view:
 * wrapped, and cut to `maxLines` with an ellipsis.
 *
 * Truncation is acceptable here and not on the map, because a row is a fixed
 * width and the full label is one hover — or one click — away.
 */
export function stepLabelLines(
  label: string,
  wrapAt: number,
  maxLines: number
): string[] {
  const lines = wrapLabel(label, wrapAt);
  if (lines.length <= maxLines) return lines;
  const shown = lines.slice(0, maxLines);
  // Trailing punctuation before an ellipsis reads as a typo.
  shown[maxLines - 1] = `${shown[maxLines - 1].replace(/[,;]?$/, '')}…`;
  return shown;
}

// ─── Geometry ────────────────────────────────────────────────────────────
//
// Shared by the canvas and by the legend, so a legend glyph is drawn by the
// same function as the node it stands for.

export function nodeRadius(node: ConstellationNode, shown = 0): number {
  if (node.type === 'decision') return 3.4 + node.priority / 11;
  if (node.type === 'system') return 6 + Math.sqrt(shown || 1) * 2.1;
  return 8 + Math.sqrt(shown || 1) * 1.5;
}

export function nodeShapePath(node: ConstellationNode, shown = 0): string {
  const r = nodeRadius(node, shown);
  if (node.type === 'department') return `M${-r} ${-r}H${r}V${r}H${-r}Z`;
  if (node.type === 'system') return `M0 ${-r * 1.25}L${r * 1.25} 0L0 ${r * 1.25}L${-r * 1.25} 0Z`;
  if (node.type === 'process') return `M0 ${-r * 1.3}L${r * 1.15} ${r * 0.75}L${-r * 1.15} ${r * 0.75}Z`;
  return `M0 0m${-r} 0a${r} ${r} 0 1 0 ${r * 2} 0a${r} ${r} 0 1 0 ${-r * 2} 0`;
}

/** Wrap a decision label for the centre of the focus view. */
export function wrapLabel(label: string, maxLength = 24): string[] {
  const lines: string[] = [];
  let line = '';
  for (const word of label.split(/\s+/)) {
    if (`${line} ${word}`.trim().length > maxLength) {
      lines.push(line.trim());
      line = word;
    } else {
      line = `${line} ${word}`.trim();
    }
  }
  if (line) lines.push(line);
  return lines;
}
