/**
 * Document writers, asserted against the real generated bytes.
 *
 * The LabMat is re-opened with `exceljs` and read cell by cell; the CheckList
 * is unzipped and its `word/document.xml` inspected. What is tested is
 * therefore what Excel and Word will show, not what the builder intended —
 * the same discipline AD-12 established for the install assessment's `.docx`.
 *
 * The templates are read from disk here rather than through
 * `lib/quoting/templates.ts`, which fetches a Vite asset URL and needs a
 * browser. Keeping the writers pure over bytes is what makes that possible.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import JSZip from 'jszip';

import {
  CHECKLIST_PLACEHOLDERS,
  PM_CONTINGENCY_CODE,
  PM_LEVELS
} from '../../config/sapQuoteGeneratorModel';
import {
  computeTotals,
  costedPhases,
  createBlankQuote,
  defaultsForProjectType,
  formatPercent,
  resolveScope,
  type QuoteState
} from './sapQuoteGenerator';
import { LABMAT_LAYOUT, buildLabmat, planLabmatRows } from './sapQuoteLabmat';
import {
  buildChecklist,
  escapeXml,
  expandPlaceholderParagraph,
  inclusionBullets,
  mergeAdjacentRuns,
  stripProofingMarkers
} from './sapQuoteChecklist';

const TEMPLATES = join(__dirname, 'templates');
const LABMAT_TEMPLATE = readFileSync(join(TEMPLATES, 'blank-bia-labmat.xlsx'));
const CHECKLIST_TEMPLATE = readFileSync(join(TEMPLATES, 'blank-checklist.docx'));

function bytes(buffer: Buffer): ArrayBuffer {
  return buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength
  ) as ArrayBuffer;
}

const STATE: QuoteState = {
  ...createBlankQuote('2026-08-05'),
  solutionArchitect: 'Mike Hobson',
  ticket: '2437170',
  client: 'Broder Group & Co',
  contactName: 'A Contact',
  contactEmail: 'a.contact@example.com',
  productStack: 'SAP Crystal Server',
  projectType: 'install',
  pricingBasis: 'Fixed',
  ...defaultsForProjectType('install'),
  hours: {
    'DI-BIA-SAP-CRY-DES-CONNECT': 0.5,
    'DI-BIA-SAP-CRY-DES-SOFTWARE': 1.5,
    'DI-BIA-SAP-CRY-BLD-MIGR-INSTALL': 7.5,
    'DI-BIA-SAP-CRY-BLD-MIGR-CONFIG': 7.5,
    'DI-BIA-SAP-CRY-BLD-MIGRATION': 7.5,
    'DI-BIA-SAP-CRY-UA-TESTING': 3.75,
    'DI-BIA-SAP-CRY-TRN-CLOUDCARE': 1
  },
  activity: { 'DI-BIA-SAP-CRY-BLD-MIGRATION': 'Initial and Go Live migrations' }
};

const TOTALS = computeTotals(STATE);

// ══════════════════════════════════════════════════════════════════════
// LabMat
// ══════════════════════════════════════════════════════════════════════

describe('LabMat row plan', () => {
  const rows = planLabmatRows(STATE, TOTALS);

  it('starts at the template body row', () => {
    expect(rows[0].row).toBe(LABMAT_LAYOUT.firstBodyRow);
  });

  it('numbers rows consecutively', () => {
    rows.forEach((row, i) => {
      expect(row.row).toBe(LABMAT_LAYOUT.firstBodyRow + i);
    });
  });

  it('stays inside the range that gets cleared', () => {
    expect(rows[rows.length - 1].row).toBeLessThanOrEqual(LABMAT_LAYOUT.lastClearedRow);
  });

  it('leads each phase with a total row and no product code', () => {
    for (const row of rows.filter((r) => r.isPhaseTotal)) {
      expect(row.code).toBe('');
      expect(row.description).toBe('');
    }
  });

  it('writes the stack name against every costed product', () => {
    for (const row of rows.filter((r) => !r.isPhaseTotal && r.code.startsWith('DI-BIA-SAP'))) {
      expect(row.stack).toBe(STATE.productStack);
    }
  });

  it('omits products with no hours', () => {
    expect(rows.some((r) => r.code === 'DI-BIA-SAP-CRY-DES-WORKSHOP')).toBe(false);
    expect(rows.every((r) => r.isPhaseTotal || r.hours > 0)).toBe(true);
  });

  it('includes derived contingency lines', () => {
    const contingency = rows.find((r) => r.code === 'DI-BIA-SAP-CRY-BLD-CONTINGENCY');
    expect(contingency).toBeDefined();
    expect(contingency!.hours).toBeCloseTo(4.5, 10);
  });

  it('ends with the PM phase, its line and its contingency', () => {
    const tail = rows.slice(-3);
    expect(tail[0].isPhaseTotal).toBe(true);
    expect(tail[0].stack).toBe('Data-Insights-BIA-Project-Management');
    expect(tail[1].code).toBe(TOTALS.pmProductCode);
    expect(tail[2].code).toBe(PM_CONTINGENCY_CODE);
  });

  it('foots the phase totals to the grand total', () => {
    const phaseHours = rows
      .filter((r) => r.isPhaseTotal)
      .reduce((n, r) => n + r.hours, 0);
    expect(phaseHours).toBeCloseTo(TOTALS.grandHours, 8);
  });

  it('has each phase total equal to the sum of its own lines', () => {
    let current: (typeof rows)[number] | undefined;
    let running = 0;
    const checks: Array<[number, number]> = [];
    for (const row of rows) {
      if (row.isPhaseTotal) {
        if (current) checks.push([current.hours, running]);
        current = row;
        running = 0;
      } else {
        running += row.hours;
      }
    }
    if (current) checks.push([current.hours, running]);
    for (const [total, sum] of checks) expect(total).toBeCloseTo(sum, 8);
  });

  it('omits the PM rows entirely when there is nothing to cost', () => {
    const empty = createBlankQuote('2026-08-05');
    expect(planLabmatRows(empty, computeTotals(empty))).toEqual([]);
  });

  it('omits the PM contingency row on target price', () => {
    const target: QuoteState = { ...STATE, pricingBasis: 'Target' };
    const plan = planLabmatRows(target, computeTotals(target));
    expect(plan.some((r) => r.code === PM_CONTINGENCY_CODE)).toBe(false);
    expect(plan.some((r) => r.code.endsWith('-TM'))).toBe(true);
  });
});

describe('generated LabMat workbook', () => {
  let sheet: import('exceljs').Worksheet;

  beforeAll(async () => {
    const out = await buildLabmat(bytes(LABMAT_TEMPLATE), STATE, TOTALS);
    const ExcelJS = await import('exceljs');
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(out);
    sheet = workbook.getWorksheet(LABMAT_LAYOUT.sheet)!;
  });

  it('keeps the LabMat sheet', () => {
    expect(sheet).toBeDefined();
  });

  it('fills the header block', () => {
    const h = LABMAT_LAYOUT.header;
    expect(sheet.getCell(h.solutionArchitect).value).toBe('Mike Hobson');
    expect(sheet.getCell(h.date).value).toBe('2026-08-05');
    expect(sheet.getCell(h.client).value).toBe('Broder Group & Co');
    expect(sheet.getCell(h.ticket).value).toBe('2437170');
    expect(sheet.getCell(h.totalServicePrice).value).toBe(TOTALS.grandValue);
  });

  it('writes the total unrounded', () => {
    expect(sheet.getCell(LABMAT_LAYOUT.header.totalServicePrice).value).toBeCloseTo(
      6177.6,
      6
    );
  });

  it('writes every planned row into the right columns', () => {
    const { columns } = LABMAT_LAYOUT;
    for (const plan of planLabmatRows(STATE, TOTALS)) {
      expect(sheet.getCell(plan.row, columns.stack).value).toBe(plan.stack);
      expect(sheet.getCell(plan.row, columns.hours).value).toBeCloseTo(plan.hours, 8);
      expect(sheet.getCell(plan.row, columns.days).value).toBeCloseTo(plan.days, 8);
      expect(sheet.getCell(plan.row, columns.value).value).toBeCloseTo(plan.value, 6);
      if (!plan.isPhaseTotal) {
        expect(sheet.getCell(plan.row, columns.code).value).toBe(plan.code);
        expect(sheet.getCell(plan.row, columns.description).value).toBe(plan.description);
      }
    }
  });

  it('carries the activity note across', () => {
    const plan = planLabmatRows(STATE, TOTALS).find(
      (r) => r.code === 'DI-BIA-SAP-CRY-BLD-MIGRATION'
    )!;
    expect(sheet.getCell(plan.row, LABMAT_LAYOUT.columns.activity).value).toBe(
      'Initial and Go Live migrations'
    );
  });

  it('bolds the phase total rows', () => {
    for (const plan of planLabmatRows(STATE, TOTALS).filter((r) => r.isPhaseTotal)) {
      expect(sheet.getCell(plan.row, LABMAT_LAYOUT.columns.stack).font?.bold).toBe(true);
      expect(sheet.getCell(plan.row, LABMAT_LAYOUT.columns.value).font?.bold).toBe(true);
    }
  });

  it('leaves nothing below the last written row', () => {
    const last = planLabmatRows(STATE, TOTALS).slice(-1)[0].row;
    for (let row = last + 1; row <= LABMAT_LAYOUT.lastClearedRow; row += 1) {
      expect(sheet.getCell(row, LABMAT_LAYOUT.columns.stack).value).toBeNull();
      expect(sheet.getCell(row, LABMAT_LAYOUT.columns.value).value).toBeNull();
    }
  });

  /*
   * The house style is the template's, so what matters is that filling it
   * did not disturb the formatting. 316 merges and the currency format on
   * the value column are the load-bearing parts.
   */
  it('preserves the template merges and number formats', () => {
    expect(Object.keys((sheet as unknown as { _merges: object })._merges)).toHaveLength(316);
    expect(sheet.getCell('AA9').numFmt).toBe('"£"#,##0.00');
    expect(sheet.getCell('U9').numFmt).toBe('0.00');
    expect(sheet.getCell(LABMAT_LAYOUT.header.totalServicePrice).numFmt).toBe(
      '"£"#,##0.00'
    );
  });

  it('rejects a workbook with no LabMat sheet', async () => {
    const ExcelJS = await import('exceljs');
    const stranger = new ExcelJS.Workbook();
    stranger.addWorksheet('Sheet1');
    const buffer = (await stranger.xlsx.writeBuffer()) as ArrayBuffer;
    await expect(buildLabmat(buffer, STATE, TOTALS)).rejects.toThrow(/no "LabMat" sheet/);
  });
});

// ══════════════════════════════════════════════════════════════════════
// CheckList
// ══════════════════════════════════════════════════════════════════════

describe('XML helpers', () => {
  it('escapes the five XML entities', () => {
    expect(escapeXml(`a & b < c > d " e ' f`)).toBe(
      'a &amp; b &lt; c &gt; d &quot; e &apos; f'
    );
  });

  it('strips proofing and bookmark markers', () => {
    const xml = '<w:p><w:proofErr w:type="spellStart"/><w:bookmarkStart w:id="1"/>x<w:bookmarkEnd w:id="1"/></w:p>';
    expect(stripProofingMarkers(xml)).toBe('<w:p>x</w:p>');
  });

  it('merges runs split across more than two elements', () => {
    const xml =
      '<w:r><w:t>&lt;&lt;con</w:t></w:r><w:r><w:t>tact_</w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t>name&gt;&gt;</w:t></w:r>';
    expect(mergeAdjacentRuns(xml)).toContain('&lt;&lt;contact_name&gt;&gt;');
  });

  it('expands a placeholder paragraph into one paragraph per bullet', () => {
    const xml =
      '<w:body><w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="3"/></w:numPr></w:pPr><w:r><w:rPr><w:sz w:val="20"/></w:rPr><w:t>&lt;&lt;dependencies&gt;&gt;</w:t></w:r></w:p></w:body>';
    const out = expandPlaceholderParagraph(xml, '<<dependencies>>', [
      { text: 'One.', level: 0 },
      { text: 'Two.', level: 1 }
    ]);
    expect(out).not.toContain('&lt;&lt;dependencies&gt;&gt;');
    expect(out.match(/<w:t xml:space="preserve">/g)).toHaveLength(2);
    // Each bullet keeps the template's numbering binding and run properties.
    expect(out.match(/<w:numId w:val="3"\/>/g)).toHaveLength(2);
    expect(out.match(/<w:sz w:val="20"\/>/g)).toHaveLength(2);
    expect(out).toContain('<w:ilvl w:val="1"/>');
  });

  it('collapses an empty list to a single empty paragraph', () => {
    const xml = '<w:p><w:pPr><w:ilvl w:val="0"/></w:pPr><w:r><w:t>&lt;&lt;assumptions&gt;&gt;</w:t></w:r></w:p>';
    const out = expandPlaceholderParagraph(xml, '<<assumptions>>', []);
    expect(out).not.toContain('&lt;&lt;assumptions&gt;&gt;');
    expect(out).toContain('<w:t></w:t>');
  });

  it('escapes bullet text as it expands', () => {
    const xml = '<w:p><w:pPr/><w:r><w:t>&lt;&lt;assumptions&gt;&gt;</w:t></w:r></w:p>';
    const out = expandPlaceholderParagraph(xml, '<<assumptions>>', [
      { text: 'Firewalls & ports <check>', level: 0 }
    ]);
    expect(out).toContain('Firewalls &amp; ports &lt;check&gt;');
  });
});

describe('inclusion bullets', () => {
  const bullets = inclusionBullets(STATE, TOTALS);

  it('nests scope items beneath their category', () => {
    const platform = bullets.findIndex((b) => b.text === 'SAP Platform Implementation Services');
    expect(platform).toBeGreaterThanOrEqual(0);
    expect(bullets[platform].level).toBe(0);
    expect(bullets[platform + 1].level).toBe(1);
  });

  it('ends with the PM tier and its deliverables', () => {
    const level = PM_LEVELS.find((l) => l.id === TOTALS.pmLevel)!;
    const index = bullets.findIndex((b) => b.text === level.label);
    expect(index).toBeGreaterThanOrEqual(0);
    expect(bullets[index].level).toBe(0);
    expect(bullets.slice(index + 1).map((b) => b.text)).toEqual(level.deliverables);
  });

  it('lists every resolved scope item', () => {
    const texts = bullets.map((b) => b.text);
    for (const category of resolveScope(STATE)) {
      expect(texts).toContain(category.label);
      for (const item of category.items) expect(texts).toContain(item);
    }
  });

  it('still carries a PM tier when nothing is in scope', () => {
    const bare: QuoteState = {
      ...STATE,
      inScope: {},
      customScope: { platform: [], training: [], other: [] }
    };
    expect(inclusionBullets(bare, TOTALS).length).toBeGreaterThan(0);
  });
});

describe('generated CheckList document', () => {
  let xml: string;

  beforeAll(async () => {
    const out = await buildChecklist(bytes(CHECKLIST_TEMPLATE), STATE, TOTALS);
    const zip = await JSZip.loadAsync(out);
    xml = await zip.file('word/document.xml')!.async('string');
  });

  it('leaves no placeholder behind', () => {
    for (const placeholder of Object.values(CHECKLIST_PLACEHOLDERS)) {
      expect(xml, placeholder).not.toContain(escapeXml(placeholder));
      expect(xml, placeholder).not.toContain(placeholder);
    }
  });

  it('fills the overview table', () => {
    expect(xml).toContain('2437170');
    expect(xml).toContain('Broder Group &amp; Co');
    expect(xml).toContain('A Contact');
    expect(xml).toContain('a.contact@example.com');
    expect(xml).toContain('Fixed');
    expect(xml).toContain(formatPercent(TOTALS.pmRate));
  });

  it('escapes an ampersand in the client name rather than emitting raw XML', () => {
    expect(xml).not.toMatch(/Broder Group & Co/);
  });

  it('writes every dependency, assumption and exclusion', () => {
    for (const text of [...STATE.dependencies, ...STATE.assumptions, ...STATE.exclusions]) {
      expect(xml, text).toContain(escapeXml(text));
    }
  });

  it('writes the inclusions with their categories', () => {
    for (const bullet of inclusionBullets(STATE, TOTALS)) {
      expect(xml, bullet.text).toContain(escapeXml(bullet.text));
    }
  });

  it('leaves the introduction empty, since the brief step is not built', () => {
    // The placeholder resolves to nothing rather than to literal text — a
    // blank section the consultant fills in, not a stray token. See AD-14.
    expect(xml).not.toContain('project_brief');
  });

  it('accepts a brief when one is supplied', async () => {
    const out = await buildChecklist(bytes(CHECKLIST_TEMPLATE), STATE, TOTALS, {
      brief: 'First line.\nSecond line.'
    });
    const zip = await JSZip.loadAsync(out);
    const withBrief = await zip.file('word/document.xml')!.async('string');
    expect(withBrief).toContain('First line.');
    expect(withBrief).toContain('<w:br/>');
    expect(withBrief).toContain('Second line.');
  });

  /*
   * Compares document parts, not archive entries: re-zipping adds explicit
   * directory entries (`word/`) that the original does not have. Word
   * ignores them, and asserting on them would pin a JSZip implementation
   * detail rather than the thing that matters — that no part was lost.
   */
  it('stays a valid docx with every part intact', async () => {
    const out = await buildChecklist(bytes(CHECKLIST_TEMPLATE), STATE, TOTALS);
    const original = await JSZip.loadAsync(bytes(CHECKLIST_TEMPLATE));
    const rebuilt = await JSZip.loadAsync(out);
    const parts = (zip: JSZip) =>
      Object.values(zip.files)
        .filter((f) => !f.dir)
        .map((f) => f.name)
        .sort();
    expect(parts(rebuilt)).toEqual(parts(original));
  });

  it('keeps the template styles part untouched', async () => {
    const out = await buildChecklist(bytes(CHECKLIST_TEMPLATE), STATE, TOTALS);
    const original = await JSZip.loadAsync(bytes(CHECKLIST_TEMPLATE));
    const rebuilt = await JSZip.loadAsync(out);
    expect(await rebuilt.file('word/styles.xml')!.async('string')).toBe(
      await original.file('word/styles.xml')!.async('string')
    );
    expect(await rebuilt.file('word/numbering.xml')!.async('string')).toBe(
      await original.file('word/numbering.xml')!.async('string')
    );
  });

  it('rejects a zip that is not a Word document', async () => {
    const zip = new JSZip();
    zip.file('hello.txt', 'not a docx');
    const buffer = await zip.generateAsync({ type: 'arraybuffer' });
    await expect(buildChecklist(buffer, STATE, TOTALS)).rejects.toThrow(
      /no word\/document\.xml/
    );
  });
});

describe('both documents agree', () => {
  it('quotes the same figure in the spreadsheet and the scope', async () => {
    const plan = planLabmatRows(STATE, TOTALS);
    const phaseHours = plan.filter((r) => r.isPhaseTotal).reduce((n, r) => n + r.hours, 0);
    expect(phaseHours).toBeCloseTo(TOTALS.grandHours, 8);

    const out = await buildChecklist(bytes(CHECKLIST_TEMPLATE), STATE, TOTALS);
    const zip = await JSZip.loadAsync(out);
    const xml = await zip.file('word/document.xml')!.async('string');
    // The CheckList states the PM rate; the LabMat prices it. If the tier
    // moved in one and not the other, the documents would contradict.
    expect(xml).toContain(formatPercent(TOTALS.pmRate));
    expect(plan.some((r) => r.code === TOTALS.pmProductCode)).toBe(true);
  });

  it('names every costed phase in the spreadsheet', () => {
    const planned = planLabmatRows(STATE, TOTALS)
      .filter((r) => r.isPhaseTotal)
      .map((r) => r.stack);
    for (const phase of costedPhases(TOTALS.phases)) {
      expect(planned).toContain(phase.name);
    }
  });
});
